package br.com.abruzzo.WebFluxReactiveAPI.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;
import lombok.NoArgsConstructor;

@DynamoDBTable(tableName = "tb_heroes")
@Data
@NoArgsConstructor
public class Hero {


    public Hero(int id, String name, String universe, int count_films) {
        this.id = id;
        this.name = name;
        this.universe = universe;
        this.countFilms = count_films;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private int id;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String universe;

    @DynamoDBAttribute
    private int countFilms;


    @Override
    public String toString() {
        return "Hero{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", universe='" + universe + '\'' +
                ", countFilms=" + countFilms +
                '}';
    }
}